// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkUX5c1GTO6CX1z1ar1f_S0aaAFJVeCsg',
    appId: '1:914987001196:web:f9c018fcae158a78313f49',
    messagingSenderId: '914987001196',
    projectId: 'wind-alarm',
    authDomain: 'wind-alarm.firebaseapp.com',
    databaseURL: 'https://wind-alarm-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wind-alarm.firebasestorage.app',
    measurementId: 'G-1KMB06P6XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoCv41EABEanZEFN5NXfiHehle8iNZ5T4',
    appId: '1:914987001196:android:090774c4f60a9425313f49',
    messagingSenderId: '914987001196',
    projectId: 'wind-alarm',
    databaseURL: 'https://wind-alarm-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wind-alarm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcYFiTo6ST7ZPNtAxqmMBivxrE-k0w8Y4',
    appId: '1:914987001196:ios:b14a7f8fc9d0e2a0313f49',
    messagingSenderId: '914987001196',
    projectId: 'wind-alarm',
    databaseURL: 'https://wind-alarm-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wind-alarm.firebasestorage.app',
    iosBundleId: 'com.example.windAlarmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcYFiTo6ST7ZPNtAxqmMBivxrE-k0w8Y4',
    appId: '1:914987001196:ios:b14a7f8fc9d0e2a0313f49',
    messagingSenderId: '914987001196',
    projectId: 'wind-alarm',
    databaseURL: 'https://wind-alarm-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wind-alarm.firebasestorage.app',
    iosBundleId: 'com.example.windAlarmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkUX5c1GTO6CX1z1ar1f_S0aaAFJVeCsg',
    appId: '1:914987001196:web:198968fa1946a671313f49',
    messagingSenderId: '914987001196',
    projectId: 'wind-alarm',
    authDomain: 'wind-alarm.firebaseapp.com',
    databaseURL: 'https://wind-alarm-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wind-alarm.firebasestorage.app',
    measurementId: 'G-MZLRGMH7E8',
  );
}
